apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ttx-web
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # Make sure there's always one instance of the transit server running.
      maxUnavailable: 1
  replicas: 3
  template:
    metadata:
      name: ttx-web
      labels:
        app: ttx-web
        # Note that version must stay stable so that the replace command knows
        # to actually tie the new replicaset with the older one, and eventually
        # scale down the old replicaset.
        version: "1"
    spec:
      # Any changes in this section will cause a new replicaset to perform a
      # rolling update of the transit server.
      containers:
      - name: ttx-web
        image: us.gcr.io/nyc-tlc-1225/ttx-web
        command: [ "yarn", "serve", "--router-url", "http://ttx-router" ]
        ports:
        - containerPort: 1337
        livenessProbe:
          httpGet:
            path: "/healthy"
            port: 1337
          initialDelaySeconds: 20
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/healthy"
            port: 1337
          initialDelaySeconds: 20
          timeoutSeconds: 2
        resources:
          requests:
            cpu: 100m  # 10% of a CPU
